// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmi5AFj7oejgE3QMak-cEh-AhdoYCkxo',
    appId: '1:86277516510:web:b652f88dfe1f29da89a64f',
    messagingSenderId: '86277516510',
    projectId: 'databasepos-99d12',
    authDomain: 'databasepos-99d12.firebaseapp.com',
    storageBucket: 'databasepos-99d12.firebasestorage.app',
    measurementId: 'G-E8ZHLH3C88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xl-dqgVi_fskINBw2RZhXSJRAkYUXUM',
    appId: '1:86277516510:android:23aebaf1de0fe4bb89a64f',
    messagingSenderId: '86277516510',
    projectId: 'databasepos-99d12',
    storageBucket: 'databasepos-99d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQM8-rSVXBRReYGceqfWZDMhH8vPKYVs8',
    appId: '1:86277516510:ios:c192fed53e0d4caa89a64f',
    messagingSenderId: '86277516510',
    projectId: 'databasepos-99d12',
    storageBucket: 'databasepos-99d12.firebasestorage.app',
    iosBundleId: 'com.example.proyekpos2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQM8-rSVXBRReYGceqfWZDMhH8vPKYVs8',
    appId: '1:86277516510:ios:c192fed53e0d4caa89a64f',
    messagingSenderId: '86277516510',
    projectId: 'databasepos-99d12',
    storageBucket: 'databasepos-99d12.firebasestorage.app',
    iosBundleId: 'com.example.proyekpos2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwmi5AFj7oejgE3QMak-cEh-AhdoYCkxo',
    appId: '1:86277516510:web:b46ca14c97718e5389a64f',
    messagingSenderId: '86277516510',
    projectId: 'databasepos-99d12',
    authDomain: 'databasepos-99d12.firebaseapp.com',
    storageBucket: 'databasepos-99d12.firebasestorage.app',
    measurementId: 'G-LCC9J8M2V9',
  );
}
